### ISSUE TITLE
rockylinux:9 missing /usr/sbin/init

### ISSUE THREAD

**Issue by eniocarboni** [eniocarboni/docker-rockylinux-systemd#3]
On rockylinux:9 is missing /usr/sbin/init, so Docker image don't start.

`Error starting container aeb98b53... 400 Client Error for http+docker://localhost... failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"/usr/sbin/init\": stat /usr/sbin/init: no such file or directory`

see https://github.com/rocky-linux/sig-cloud-instance-images/issues/39

**Comment by eniocarboni** [comment]
In the Dockerfile file added the top line:
`RUN [ ! -f /usr/sbin/init ] && dnf -y install systemd;`

See commit https://github.com/eniocarboni/docker-rockylinux-systemd/commit/fef7dc686bf54683fa776cb47461c9bd270d3d1c

**Comment by NeilHanlon** [comment]
hey - saw this in my notifications. I apologize for the lack of communication on the upstream ticket.

init was removed because it was getting pulled in as a dependency by a package that, if included, was bringing in systemd utilities which were not needed in the image.

I would recommend you check out the 9-ubi image, which does provide init and some other systemd tools.

**Comment by eniocarboni** [comment]
@NeilHanlon, thanks for the advice, I'll use both images.
